# Generated by Django 3.2.7 on 2021-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafield',
            name='help_text',
            field=models.TextField(blank=True, help_text='Optional.', null=True),
        ),
        migrations.AlterField(
            model_name='extrafield',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
